version: "3"
services:
  postgres:
    image: alexbenko/ourlife_db
    ports:
      - "5432:5432"
  redis:
    image: redis
    container_name: store
    ports:
      - '6379:6379'
    logging:
      driver: none

  app:
    image: alexbenko/ourlife_server:latest
    depends_on:
      - postgres
      - redis
    volumes:
    # obviously this is only for my local machine, path is slightly different on producton server
      - /Users/AlexB/Desktop/static:/dist/static
    environment:
      REDIS_URL: redis://store
      PORT: 8080
    ports:
      - "8080:8080"
    command: npm start

